spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: eresulovstd
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    database: postgresql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8085